import { ArrowRight, Music2, Ticket, Sparkles } from 'lucide-react';

export function HomeBannerFallback({ error, onRetry }: { error?: string; onRetry?: () => void }) {
  return <div className="relative flex min-h-[420px] items-center overflow-hidden rounded-3xl border border-white/20 bg-gradient-to-r from-violet-950 via-[#241036] to-fuchsia-950/60 p-6 shadow-2xl shadow-violet-500/20 md:min-h-[480px] md:p-12">
    <div aria-hidden="true" className="pointer-events-none absolute -right-20 -top-20 size-96 rounded-full bg-fuchsia-500/20 blur-3xl" />
    <div aria-hidden="true" className="absolute right-[12%] hidden rotate-[-12deg] rounded-[40px] border border-white/20 bg-gradient-to-r from-violet-500/15 to-fuchsia-500/15 p-12 text-fuchsia-200/60 md:block"><Ticket size={120} strokeWidth={1} /></div>
    <div className="relative max-w-2xl"><p className="mb-6 flex items-center gap-2 text-sm text-fuchsia-200"><Sparkles size={18} aria-hidden="true" />Trải nghiệm mới đang chờ bạn</p><h1 className="text-4xl font-semibold leading-tight text-white md:text-6xl">Một chiếc vé.<br />Ngàn khoảnh khắc.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/80">Khám phá những đêm nhạc, lễ hội và sự kiện để cùng nhau tạo nên những kỷ niệm đáng nhớ.</p>
    {error ? <div role="alert" className="mt-6"><p className="text-sm text-white/80">Chưa thể tải sự kiện nổi bật. Bạn có thể thử lại.</p><button onClick={onRetry} className="mt-4 rounded-2xl bg-gradient-to-r from-violet-600 to-fuchsia-600 bg-[length:200%_auto] px-6 py-3 font-medium text-white transition-all duration-300 hover:bg-right hover:shadow-xl hover:shadow-violet-500/40 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-violet-300 motion-reduce:transition-none">Thử lại</button></div> : <div className="mt-8 flex items-center gap-2 text-sm text-white/70"><Music2 size={18} aria-hidden="true" />Concert · Festival · Workshop</div>}
    <a href="#home-search" className="mt-6 inline-flex items-center gap-3 rounded-2xl border border-white/20 px-6 py-3 font-medium text-white transition-all duration-300 hover:border-fuchsia-300/50 hover:shadow-xl hover:shadow-violet-500/25 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-violet-300 motion-reduce:transition-none">Tìm sự kiện của bạn<ArrowRight size={18} aria-hidden="true" /></a></div>
  </div>;
}
