import type { TicketListing } from './tickets-marketplace.types';

export const mockTicketListings: TicketListing[] = [
  {
    id: 'TKT-PASS-001',
    eventId: 'any',
    tierName: 'VIP 1 Diamond',
    tierColor: 'violet',
    zone: 'Khu A1 - Chính diện sân khấu',
    seatNumber: 'Hàng D, Ghế 12 - 13',
    quantity: 2,
    isAdjacentSeats: true,
    originalPrice: 2800000,
    resalePrice: 2500000,
    ticketType: 'eticket',
    seller: {
      id: 'usr_8492',
      name: 'Tuấn Minh',
      reputationScore: 4.9,
      successfulSales: 38,
      isIdentityVerified: true,
    },
    note: 'Bận việc gia đình đột xuất pass lại 2 vé cạnh nhau, chuyển quyền sở hữu qua app trong 5 phút.',
    createdAt: '10 phút trước',
  },
  {
    id: 'TKT-PASS-002',
    eventId: 'any',
    tierName: 'GA Stand A',
    tierColor: 'emerald',
    zone: 'Khu đứng Fanzone A',
    seatNumber: 'Đứng tự do',
    quantity: 1,
    isAdjacentSeats: false,
    originalPrice: 1200000,
    resalePrice: 950000,
    ticketType: 'eticket',
    seller: {
      id: 'usr_5321',
      name: 'Khánh Linh',
      reputationScore: 5.0,
      successfulSales: 16,
      isIdentityVerified: true,
    },
    note: 'Vé chính chủ Fanzone, hỗ trợ vào cổng trực tiếp nếu cần.',
    createdAt: '25 phút trước',
  },
  {
    id: 'TKT-PASS-003',
    eventId: 'any',
    tierName: 'CAT 1 Khán đài',
    tierColor: 'blue',
    zone: 'Khán đài A - Tầng 2',
    seatNumber: 'Hàng F, Ghế 08 - 09 - 10',
    quantity: 3,
    isAdjacentSeats: true,
    originalPrice: 1800000,
    resalePrice: 1650000,
    ticketType: 'eticket',
    seller: {
      id: 'usr_9912',
      name: 'Hoàng Nam',
      reputationScore: 4.8,
      successfulSales: 52,
      isIdentityVerified: true,
    },
    note: 'Cả nhóm 3 người có lịch thi nên pass lại nguyên combo 3 ghế liền kề view thẳng.',
    createdAt: '1 giờ trước',
  },
  {
    id: 'TKT-PASS-004',
    eventId: 'any',
    tierName: 'VIP 2 Sapphire',
    tierColor: 'violet',
    zone: 'Khu B1 - Cánh phải sân khấu',
    seatNumber: 'Hàng C, Ghế 05',
    quantity: 1,
    isAdjacentSeats: false,
    originalPrice: 2200000,
    resalePrice: 1950000,
    ticketType: 'physical',
    seller: {
      id: 'usr_3211',
      name: 'Thanh Thảo',
      reputationScore: 4.95,
      successfulSales: 24,
      isIdentityVerified: true,
    },
    note: 'Đã nhận vé cứng và vòng tay VIP, giao dịch trực tiếp tại TP.HCM hoặc ship hỏa tốc.',
    createdAt: '2 giờ trước',
  },
  {
    id: 'TKT-PASS-005',
    eventId: 'any',
    tierName: 'CAT 2 Khán đài',
    tierColor: 'amber',
    zone: 'Khán đài B - Cửa 6',
    seatNumber: 'Hàng K, Ghế 21 - 22',
    quantity: 2,
    isAdjacentSeats: true,
    originalPrice: 1100000,
    resalePrice: 850000,
    ticketType: 'eticket',
    seller: {
      id: 'usr_1042',
      name: 'Đức Anh',
      reputationScore: 4.7,
      successfulSales: 9,
      isIdentityVerified: true,
    },
    note: 'Pass rẻ 2 vé cho bạn nào đi xem cùng người yêu, giá tốt nhất phân khúc.',
    createdAt: '3 giờ trước',
  },
  {
    id: 'TKT-PASS-006',
    eventId: 'any',
    tierName: 'VVIP Premium Lounge',
    tierColor: 'rose',
    zone: 'Khu vực Lounge đặc biệt',
    seatNumber: 'Bàn V-04 (Bao gồm Tea-break & Merch)',
    quantity: 2,
    isAdjacentSeats: true,
    originalPrice: 4500000,
    resalePrice: 4200000,
    ticketType: 'eticket',
    seller: {
      id: 'usr_7721',
      name: 'Phương Uyên',
      reputationScore: 5.0,
      successfulSales: 41,
      isIdentityVerified: true,
    },
    note: 'Full quyền lợi soundcheck, quà tặng merch độc quyền và lối đi riêng không phải xếp hàng.',
    createdAt: '5 giờ trước',
  },
];
